# Generated by Django 5.2.1 on 2025-06-03 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('colgante', 'Colgante'), ('pulsera', 'Pulsera'), ('collar', 'Collar'), ('anillo', 'Anillo'), ('arete', 'Arete')], max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
