# Generated by Django 5.2.1 on 2025-06-03 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('oro', 'Oro'), ('plata', 'Plata'), ('oro_bajo', 'Oro Bajo')], max_length=50, verbose_name='Tipo Material')),
            ],
        ),
    ]
