# Generated by Django 5.2.2 on 2025-06-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='tipo',
            field=models.CharField(max_length=50, verbose_name='Tipo Material'),
        ),
    ]
